<a href="https://colab.research.google.com/github/Carmen10-171/01MIAR_ABR26/blob/main/01MIAR_Exam_02_B_Solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Examen Primera Convocatoria Franja Tarde

In [ ]:
# Your imports HERE !!!!
from os import path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 01 - Diccionario de funciones (1 pto)

Crea un diccionario llamado `my_divs` que guarde en su clave `1` una función que divida dos números y en su clave `2` una función similar, pero que realice una división entera.

In [ ]:
# Your code HERE
my_divs = {
    1: lambda a, b: a / b, # división normal
    2: lambda a, b: a // b # división entera
}

In [ ]:
# Test Use Case
assert(my_divs[1](7,2) == 3.5)
assert(my_divs[2](7,2) == 3)

print(my_divs[1](7,2))
print(my_divs[2](7,2))

3.5
3

In [ ]:
def div(a, b):
    return a / b

def div_entera(a, b):
    return a // b

my_divs = {
    1: div,
    2: div_entera
}

# Test Use Case
assert(my_divs[1](7,2) == 3.5)
assert(my_divs[2](7,2) == 3)
print(my_divs[1](7,2))
print(my_divs[2](7,2))

3.5
3

## 02 - Señal de prueba (2 ptos)

Crea una función `test_signal(l, **kwargs)` que devuelva un array de numpy binomial que contiene sólo `1`s y `0`s arreglados de forma aleatoria y con una probabilidad de 50%/50%. La longitud del array está definida por el parámetro `l` cuyo valor por defecto es 10. Cómo parámetros opcionales puedes pasar una semilla `s` para que la función retorne consistentemente los mismos valores o una nueva probabilidad `p` con la que aparecerá el `1`.

Revisar [documentación](https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html).

In [ ]:
# Your code HERE
def test_signal(l=10, **kwargs):

     p = kwargs.get("p", 0.5)

     s = kwargs.get("s", None)

     if s is not None:
        np.random.seed(s)

     return np.random.binomial(1, p, l)

In [ ]:
# Test Use Case
output1 = test_signal()
print(f"Señal por defecto: {output1}")
assert(len(output1) == 10)

output2 = test_signal(5)
print(f"Señal de 5 valores: {output2}")
assert(len(output2) == 5)

output3 = test_signal(30, p=0)
display(f"Señal con 30 0s: {output3}")
assert(output3.sum() == 0)

output4 = test_signal(300, s=42)
output5 = test_signal(300, s=42)
assert((output4 == output5).all())

Señal por defecto: [0 1 1 1 1 1 1 0 1 0]
Señal de 5 valores: [0 0 0 1 1]

'Señal con 30 0s: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]'

In [ ]:
# Hacér documentación.

def test_siguil(le20, valueArg):
    r = random.choice(range(valueArg.get('c', 3000)))
    p = valueArg.get('p', 0.5)
    return (r, random.binomial(1, p, size=r))

In [ ]:
# Test Use Case
output1 = test_signal()
print(f"Señal por defecto: {output1}")
assert(len(output1) == 10)

output2 = test_signal(5)
print(f"Señal de 5 valores: {output2}")
assert(len(output2) == 5)

output3 = test_signal(30, p=0)
display(f"Señal con 30 0s: {output3}")
assert(output3.sum() == 0)

output4 = test_signal(300, s=42)
output5 = test_signal(300, s=42)
assert((output4 == output5).all())

Señal por defecto: [0 1 1 1 1 1 1 0 1 0]
Señal de 5 valores: [0 0 0 1 1]

'Señal con 30 0s: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]'

## 03 Extraer de texto - (2 ptos)

Adjunto encontrarás un fichero llamado **texto.txt**. Crea un conjunto (set) que contenga todas las palabras en este fichero que comiencen por la letra **e**. Para ello convierte todas las mayúsculas en minúsculas y elimina espacios, caracteres de nueva línea y los signos de puntuación **"."** y **","** antes de guardarlos en el conjunto.

In [ ]:
# Your code HERE
# Your code HERE
def extract_words_starting_with_e(filename):

    with open(filename, "r", encoding="utf-8") as f:
        texto = f.read().lower()

    texto = texto.replace("\n", " ")
    texto = texto.replace(".", "")
    texto = texto.replace(",", "")

    palabras_e = {
        palabra
        for palabra in texto.split()
        if palabra.startswith("e")
    }

    return palabras_e

In [ ]:
def extract_words_starting_with_e(filename):
    with open(filename, "r", encoding="utf-8") as f:
        resultado = set()

        for line in f.readlines():
            for word in line.split():
                w = word.lower()
                w = w.replace(".", "").replace(",", "")
                w = w.replace("?", "").replace("!", "")

                if w.startswith("e"):
                    resultado.add(w)

    return resultado

In [ ]:
# Test Use Case
filename = "texto.txt"

expected_output = {'etiam', 'eleifend', 'eu', 'enim', 'est', 'eget', 'elementum', 'ex',
                   'elit', 'egestas', 'euismod', 'efficitur', 'et', 'eros', 'erat'}

output = extract_words_starting_with_e(filename)
display(output)

assert(output == expected_output)

{'efficitur',
 'egestas',
 'eget',
 'eleifend',
 'elementum',
 'elit',
 'enim',
 'erat',
 'eros',
 'est',
 'et',
 'etiam',
 'eu',
 'euismod',
 'ex'}

## 04 Bicis - (5 ptos)

Adjunto encontrarás un fichero llamado **bicis.csv** que contiene los datos de uso de bicicletas de alquiler del mes de julio del año 2021. El objetivo de esta actividad es la de transformar los datos para obtener un nuevo dataframe con estadísticas agrupadas por estación:

El dataset original contiene las siguientes columnas:
 - **ride_id:** Identificador único del viaje.
 - **rideable_type:** Tipo de bicicleta que se ha usado en el viaje.
 - **started_at:** Fecha de inicio del viaje.
 - **ended_at:** Fecha de finalización del viaje.
 - **start_station_name:** Nombre de la estación de partida.
 - **start_station_id:** Identificador de la estación de partida.
 - **end_station_name:** Nombre de la estación de llegada.
 - **end_station_id:** Identificador de la estación de llegada.
 - **start_lat:** Latitud de partida.
 - **start_lng:** Longitud de partida.
 - **end_lat:** Latitud de llegada.
 - **end_lng:** Longitud de llegada.
 - **member_casual:** Tipo de usuario durante el viaje.

El dataset que queremos al final debe tener las siguientes columnas:
 - **station_id:** Identificador de la estación (referida como la estación de partida).
 - **total_rides:** Viajes totales iniciados en la estatión.
 - **start_member_percentage:** Porcentaje de usuarios miembros (valor `member` en la columna `member_casual`) que han iniciado el viaje desde esta estación (cantidad member / total usuarios).
 - **most_common_end_station_id:** Identificador de la estación destino más frecuente al iniciar el viaje desde esta estación.
 - **mean_duration:** Media de duración del viaje que comience en esta estación.
 - **rideable_type_count:** Una columna por cada tipo único de `rideable_type` con la cantidad de tipos de bicicletas que comenzaron el viaje desde esta estación.

In [ ]:
# Your code HERE
# 1. Carga de datos de csv (bicis.csv) en un DataFrame
loaded=pd.read_csv('bicis.csv')
df =loaded[['start_station_id', 'ride_id', 'member_casual','end_station_id', 'rideable_type' ]].copy()

#mask = df["start_member_percetage"] == 100* df["ride_id"].sum() / (df["member_casual"])

#df['station_id'] = pd.update(df['start_station_id'])
display(df.head(5))

,start_station_id,ride_id,member_casual,end_station_id,rideable_type
0,13001,0A1B623926EF4E16,casual,KA1504000117,docked_bike
1,17660,B2D5583A5A5E76EE,casual,13432,classic_bike
2,SL-012,6F264597DDBF427A,member,KA1503000044,classic_bike
3,17660,379B58EAB20E8AA5,member,13196,classic_bike
4,17660,6615C1E4EB08E8FB,casual,13197,electric_bike

In [ ]:
import pandas as pd

# Cargar datos
df = pd.read_csv("bicis.csv")

# Convertir fechas a datetime
df["started_at"] = pd.to_datetime(df["started_at"])
df["ended_at"] = pd.to_datetime(df["ended_at"])

# Calcular duración del viaje en minutos
df["duration"] = (
    df["ended_at"] - df["started_at"]
).dt.total_seconds() / 60

Qué hace: Cuenta cuántos registros son member y cuántos casual.
Obtiene el número de member.
Lo divide entre el total de filas del dataframe.

In [ ]:
# Calcular duración del viaje en minutos
df['duration'] = (pd.to_datetime(df['ended_at']) - pd.to_datetime(df['started_at']))/60

display(df.head(3))

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,duration
0,0A1B623926EF4E16,docked_bike,2021-07-02 14:44:36,2021-07-02 15:19:58,Michigan Ave & Washington St,13001,Halsted St & North Branch St,KA1504000117,41.883984,-87.624684,41.899368,-87.648480,casual,0 days 00:00:35.366666
1,B2D5583A5A5E76EE,classic_bike,2021-07-07 16:57:42,2021-07-07 17:16:09,California Ave & Cortez St,17660,Wood St & Hubbard St,13432,41.900363,-87.696704,41.889899,-87.671473,casual,0 days 00:00:18.450000
2,6F264597DDBF427A,classic_bike,2021-07-25 11:30:55,2021-07-25 11:48:45,Wabash Ave & 16th St,SL-012,Rush St & Hubbard St,KA1503000044,41.860384,-87.625813,41.890173,-87.626185,member,0 days 00:00:17.833333

In [ ]:
# Crear un grupo por estación de partida
station_id_groupby = df.groupby("start_station_id")
print(station_id_groupby.count().index)

Index(['13001', '13006', '13008', '13011', '13016', '13017', '13021', '13022',
       '13028', '13029',
       ...
       'TA1309000058', 'TA1309000059', 'TA1309000061', 'TA1309000063',
       'TA1309000064', 'TA1309000066', 'TA1309000067', 'WL-008', 'WL-011',
       'WL-012'],
      dtype='str', name='start_station_id', length=710)

Qué hace: Cuenta cuántas veces aparece cada end_station_id.
idxmax() devuelve el identificador con mayor frecuencia.

In [ ]:
# Porcentaje de miembros (member)
def member_percentage(df):
    counts = df['member_casual'].value_counts()
    return counts.get('member', 0) / len(df)

print(member_percentage(df))

0.46248708065320215

In [ ]:
# Estación de llegada más frecuente
def most_common_end_station(df):
    counts = df['end_station_id'].value_counts()
    return counts.idxmax()

print(most_common_end_station(df))

13022

In [ ]:
def most_common_end_station(df):
    counts = df['end_station_id'].value_counts()
    return counts.idxmax() if not counts.empty else None
print(most_common_end_station(df))

13022

Qué hace: Compara cada valor de la serie con 'docked_bike'. Obtiene un array de True/False. .sum() cuenta los True

In [ ]:
# Crear una que devuelva las ocurrencias de un valor específico en una columna específica.
def count_value_in_column(value, series):
    return (series == value).sum()

count_value_in_column('docked_bike', df['rideable_type'])
print(count_value_in_column('docked_bike', df['rideable_type']))
print(df[['start_station_id','end_station_id']].head())

57698
  start_station_id end_station_id
0            13001   KA1504000117
1            17660          13432
2           SL-012   KA1503000044
3            17660          13196
4            17660          13197

In [ ]:
# Iterar sobre el grupo y construir el nuevo dataframe utilizando las funciones definidas anteriormente.
stations = list()

for station_id, df_view in station_id_groupby:
    new_row = dict()

    new_row['station_id'] = station_id
    new_row['total_rides'] = len(df_view)
    new_row['start_member_percentage'] = member_percentage(df_view)
    new_row['most_common_end_station_id'] = most_common_end_station(df_view)
    new_row['mean_duration'] = df_view['duration'].mean()

    for bike_type in df_view['rideable_type'].unique():
        new_row[bike_type] = count_value_in_column(
            bike_type,
            df_view['rideable_type']
        )

    stations.append(new_row)

stations_df = pd.DataFrame(stations)
stations_df.head(10)

,station_id,total_rides,start_member_percentage,most_common_end_station_id,mean_duration,docked_bike,classic_bike,electric_bike
0,13001,4097,0.367098,13001,0 days 00:00:39.224354,606.0,2678.0,813.0
1,13006,1309,0.562261,13006,0 days 00:00:50.979335,93.0,871.0,345.0
2,13008,7653,0.170391,13008,0 days 00:00:53.607251,1834.0,4555.0,1264.0
3,13011,2485,0.588330,13011,0 days 00:00:19.549577,171.0,1709.0,605.0
4,13016,4472,0.500447,13016,0 days 00:00:28.790231,474.0,2939.0,1059.0
5,13017,1919,0.574779,TA1308000050,0 days 00:00:30.980171,71.0,1410.0,438.0
6,13021,2550,0.598431,13021,0 days 00:00:14.809751,96.0,1791.0,663.0
7,13022,17013,0.159937,13022,0 days 00:00:43.053807,4327.0,10292.0,2394.0
8,13028,869,0.669735,13332,0 days 00:00:17.339278,32.0,668.0,169.0
9,13029,1491,0.157612,13022,0 days 00:00:33.210764,381.0,830.0,280.0